sonar.projectKey=HarisNaseer7_Harisnaseer-mern-10pshine
sonar.organization=harisnaseer7
sonar.projectName=NoteApp Frontend
sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.jsx,src/__tests__/**/*.test.js
sonar.exclusions=**/node_modules/**,**/coverage/**,src/__tests__/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info