sonar.projectKey=HarisNaseer7_Harisnaseer-mern-10pshine
sonar.organization=harisnaseer7
sonar.projectName=NoteApp Frontend
sonar.sources=src
sonar.tests=src/__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/coverage/**