sonar.projectKey=HarisNaseer7_Harisnaseer-mern-10pshine
sonar.organization=harisnaseer7
sonar.projectName=10P-Shine-MERN
sonar.projectVersion=1.0
sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,**/test/**,**/__tests__/**
